version: '3.7'

services:
    sqlserver1:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:  
          - "1444:1433"
        environment:
          - ACCEPT_EULA=
          - SA_PASSWORD=jonas123!
        volumes: 
          - ./sqldata:/var/lib/mssqlql/data
volumes:
  sqldata: